# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: huecli

builds:
  - binary: huecli
    env: 
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch: 
      - amd64
      - arm64
    main: ./cmd/huecli/main.go

release:
  prerelease: auto

universal_binaries:
  - replace: true

homebrew_casks:
  -
    name: huecli
    skip_upload: auto
    homepage: https://github.com/MoAlshatti/hue-bridge-TUI
    repository:
      owner: MoAlshatti
      name: homebrew-tap
    commit_author:
      name: Mohammad Alshatti
      email: furyzlm.eap@gmail.com

checksum: 
  name_template: 'checksums.txt'
